//
//  ViewController.swift
//  WeAchieve
//
//  Created by Miguel Batilando on 7/23/18.
//  Copyright © 2018 Make School. All rights reserved.
//

import UIKit
import Firebase
import FirebaseAuth
import FirebaseDatabase

class SearchViewController: UIViewController, UITableViewDataSource, UISearchBarDelegate, SearchCellDelegate, UITableViewDelegate {
    
    // MARK: - Outlets
    @IBOutlet var searchView: UIView!
    @IBOutlet weak var opportunityTableView: UITableView!
    @IBOutlet weak var searchBar: UISearchBar!
    
    // MARK: - Variables
    let userID = Auth.auth().currentUser?.uid
    let favoritesVC = FavoritesViewController(nibName: "FavoritesViewController", bundle: nil)
    var isLiked = false
    var ref: DatabaseReference! = Database.database().reference()
    var likedInternships = [Internship]()
    var likedScholarships = [Scholarship]()
    var internshipArray = [Internship]()
    var scholarshipArray = [Scholarship]()
    var searchInternship = [Internship]()
    var searchScholarship = [Scholarship]()
    var isSearching = false
    var buttonState = false
    
    override func viewDidLoad() {
        super.viewDidLoad()
        searchBar.delegate = self
        searchBar.layer.borderWidth = 1
        searchBar.layer.borderColor = Colors.linkedInBlue.cgColor
        setupInternships()
        setupScholarships()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
    }
    
    func searchBar(_ searchBar: UISearchBar, selectedScopeButtonIndexDidChange selectedScope: Int) {
        opportunityTableView.reloadData()
    }
    
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        if searchBar.selectedScopeButtonIndex == 0 {
            searchInternship = internshipArray.filter({$0.description.contains(searchText)})
            isSearching = true
            opportunityTableView.reloadData()
        } else {
            searchScholarship = scholarshipArray.filter({$0.description.contains(searchText)})
            isSearching = true
            opportunityTableView.reloadData()
        }
    }
    
    func searchBarCancelButtonClicked(_ searchBar: UISearchBar) {
        isSearching = false
        view.endEditing(true)
        opportunityTableView.reloadData()
    }
    
    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        view.endEditing(true)
        opportunityTableView.reloadData()
    }
    
    func likeButtonPressedForInternship(intershipVar: Internship) {
        intershipVar.isLiked = !intershipVar.isLiked
        if intershipVar.isLiked == true {
            if likedInternships.contains(where: {$0.title == intershipVar.title}) {
                let alert = UIAlertController(title: "Already in favorites!", message: nil, preferredStyle: .alert)
                let okButton = UIAlertAction(title: "OK", style: .default, handler: nil)
                alert.addAction(okButton)
                self.present(alert, animated: true, completion: nil)
            } else {
                let alert = UIAlertController(title: "Added to favorites! ", message: nil, preferredStyle: .alert)
                let okButton = UIAlertAction(title: "OK", style: .default, handler: nil)
                alert.addAction(okButton)
                self.present(alert, animated: true, completion: nil)
                likedInternships.append(intershipVar)
            }
        }
        let dict = intershipVar.convertToDict()
        ref?.child("Users").child(userID!).child("Internships").childByAutoId().updateChildValues(dict)
    }
    
    func likeButtonPressedForScholarship(scholarshipVar: Scholarship) {
        scholarshipVar.isLiked = !isLiked
        if scholarshipVar.isLiked == true {
            if likedScholarships.contains(where: {$0.title == scholarshipVar.title}) {
                let alert = UIAlertController(title: "Already in favorites!", message: nil, preferredStyle: .alert)
                let okButton = UIAlertAction(title: "OK", style: .default, handler: nil)
                alert.addAction(okButton)
                self.present(alert, animated: true, completion: nil)
            } else {
                let alert = UIAlertController(title: "Added to favorites!", message: nil, preferredStyle: .alert)
                let okButton = UIAlertAction(title: "OK", style: .default, handler: nil)
                alert.addAction(okButton)
                self.present(alert, animated: true, completion: nil)
                likedScholarships.append(scholarshipVar)
            }
        }
        let dict = scholarshipVar.convertToDict()
        ref?.child("Users").child(userID!).child("Scholarships").childByAutoId().updateChildValues(dict)
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        
        if isSearching {
            if searchBar.selectedScopeButtonIndex == 0 {
                return searchInternship.count
            } else {
                return searchScholarship.count
            }
        } else {
            if searchBar.selectedScopeButtonIndex == 0 {
                return internshipArray.count
            } else {
                return scholarshipArray.count
            }
        }
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let internshipCell = tableView.dequeueReusableCell(withIdentifier: "internshipCell", for: indexPath) as! SearchViewControllerCell
        let scholarshipCell = tableView.dequeueReusableCell(withIdentifier: "scholarshipCell", for: indexPath) as! SearchViewControllerCell
        
        if isSearching {
            if searchBar.selectedScopeButtonIndex == 0 {
                internshipCell.title.text = searchInternship[indexPath.row].title
                internshipCell.title.lineBreakMode = .byTruncatingTail
                internshipCell.companyOrAmount.text = searchInternship[indexPath.row].company
                internshipCell.locationOrDeadline.text = searchInternship[indexPath.row].location
                internshipCell.delegate = self
                internshipCell.isScholarship = false
                internshipCell.internshipVar = searchInternship[indexPath.row]
                return internshipCell
            } else {
                scholarshipCell.title.text = searchScholarship[indexPath.row].title
                scholarshipCell.companyOrAmount.text = searchScholarship[indexPath.row].amount
                scholarshipCell.locationOrDeadline.text = searchScholarship[indexPath.row].deadline
                scholarshipCell.delegate = self
                scholarshipCell.isScholarship = true
                scholarshipCell.schoalrshipVar = searchScholarship[indexPath.row]
                return scholarshipCell
            }
        } else {
        if searchBar.selectedScopeButtonIndex == 0 {
            internshipCell.title.text = internshipArray[indexPath.row].title
            internshipCell.companyOrAmount.text = internshipArray[indexPath.row].company
            internshipCell.locationOrDeadline.text = internshipArray[indexPath.row].location
            internshipCell.delegate = self
            internshipCell.isScholarship = false
            internshipCell.internshipVar = internshipArray[indexPath.row]
            return internshipCell
        } else {
            scholarshipCell.title.text = scholarshipArray[indexPath.row].title
            scholarshipCell.companyOrAmount.text = scholarshipArray[indexPath.row].amount
            scholarshipCell.locationOrDeadline.text = scholarshipArray[indexPath.row].deadline
            scholarshipCell.delegate = self
            scholarshipCell.isScholarship = true
            scholarshipCell.schoalrshipVar = scholarshipArray[indexPath.row]
            return scholarshipCell
        }
    }
        
    }
    
    
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let InternshipVC = storyboard?.instantiateViewController(withIdentifier: "InternshipViewController") as! InternshipDetailsViewController
        let ScholarshipsVC = storyboard?.instantiateViewController(withIdentifier: "ScholarshipViewController") as! ScholarshipsDetailsViewController
        
        if searchBar.selectedScopeButtonIndex == 0 && !searchInternship.isEmpty {
        InternshipVC.internshipName = searchInternship[indexPath.row].title
        InternshipVC.internshipCo = searchInternship[indexPath.row].company
        InternshipVC.internshipLoc = searchInternship[indexPath.row].location
        InternshipVC.internshipDesc = searchInternship[indexPath.row].description
        InternshipVC.internshipURL = searchInternship[indexPath.row].url
        tableView.deselectRow(at: indexPath, animated: true)
        self.navigationController?.pushViewController(InternshipVC, animated: true)
        } else if searchBar.selectedScopeButtonIndex == 1 && !searchScholarship.isEmpty {
            ScholarshipsVC.scholarshipName = searchScholarship[indexPath.row].title
            ScholarshipsVC.scholarshipAmnt = searchScholarship[indexPath.row].amount
            ScholarshipsVC.scholarshipDueDate = searchScholarship[indexPath.row].deadline
            ScholarshipsVC.scholarshipDesc = searchScholarship[indexPath.row].description
            ScholarshipsVC.scholarshipURL = searchScholarship[indexPath.row].url
            tableView.deselectRow(at: indexPath, animated: true)
            self.navigationController?.pushViewController(ScholarshipsVC, animated: true)
        } else if searchBar.selectedScopeButtonIndex == 0 {
            InternshipVC.internshipName = internshipArray[indexPath.row].title
            InternshipVC.internshipCo = internshipArray[indexPath.row].company
            InternshipVC.internshipLoc = internshipArray[indexPath.row].location
            InternshipVC.internshipDesc = internshipArray[indexPath.row].description
            InternshipVC.internshipURL = internshipArray[indexPath.row].url
            tableView.deselectRow(at: indexPath, animated: true)
            self.navigationController?.pushViewController(InternshipVC, animated: true)
        } else {
            ScholarshipsVC.scholarshipName = scholarshipArray[indexPath.row].title
            ScholarshipsVC.scholarshipAmnt = scholarshipArray[indexPath.row].amount
            ScholarshipsVC.scholarshipDueDate = scholarshipArray[indexPath.row].deadline
            ScholarshipsVC.scholarshipDesc = scholarshipArray[indexPath.row].description
            ScholarshipsVC.scholarshipURL = scholarshipArray[indexPath.row].url
            tableView.deselectRow(at: indexPath, animated: true)
            self.navigationController?.pushViewController(ScholarshipsVC, animated: true)
        }
        
        
    }
    
    // MARK: - Opportunities
    private func setupInternships() {
        internshipArray.append(Internship(title: "AAAS Minority Science Writers Internship", company: "AAAS", location: "New York", description: "The AAAS Minority Science Writers Internship places minority students interested in journalism as a career and who want to learn about science writing at Science Magazine for 10 weeks in the summer. Interns will cover the scientific and technological issues across the globe. This program is open to undergraduate minorities with a serious interest in science writing. Students pursuing a journalism major are given preference. Applicant must be in an academic program. Required materials: resume, unofficial transcripts, and two writing samples. One should be about a news event that took place after October 15. Application Essay: In less than 800 words, tell us about yourself and your interest in this internship: commitment to journalism, your thoughts about science and science writing, your career goals, and what you hope to get out of this internship.", url: "https://www.aaas.org/page/aaas-minority-science-writers-internship", isLiked: false))
        internshipArray.append(Internship(title: "Interpublic Group Scholarship and Internship", company: "Interpublic Group", location: "New York, NY", description: "The New York Women in Communications Foundation, in alliance with New York Women in Communications, awards the Interpublic Group Scholarship and Internship annually based on academic excellence, need and involvement in the field of communications. An award is given to an ethnically diverse student who is currently a college junior and has an interest advertising or public relations. Potential candidates must be able to fulfill a paid internship during the summer prior to the academic year the scholarship is offered. Eligibility: Must be a U.S. citizen or a permanent resident who live in NY, NJ, CT, or PA, college undergraduate and graduate students who are permanent residents of one of these states, be majoring or planning to declare a major or pursuing an advanced degree in advertising or public relations and have an overall GPA of 3.2+.", url: "https://scholarships.nywici.org/sponsored-scholarships", isLiked: false))
        internshipArray.append(Internship(title: "Smithsonian Institution James E. Webb Internship", company: "Smithsonian", location: "Washington, DC", description: "This program honors James. E. Webb, Regent Emeritus and former Administrator of the National Aeronautics and Space Administration, to promote excellence in the management of not-for-profit organizations. These opportunities are intended to increase participation of groups of the minority who are under-represented in the management of scientific and cultural organizations. Interns are situated in offices, museums, and research institutes throughout the Smithsonian Institution. Eligibility: Must be a U.S. citizens and U.S. permanent resident, must be enrolled in an undergraduate or in a graduate program of study in business or public administration. Students are expected to have a 3.0+ GPA", url: "https://www.smithsonianofi.com/internship-opportunities/james-e-webb-internship/", isLiked: false))
        internshipArray.append(Internship(title: "Tampa Bay Times Peterman Scholarship/News Internship", company: "Tampa Bay Times", location: "St. Petersburg, FL", description: "Only students who are hired as part of the Summer Internship Program at the Times are eligible to apply for the Tampa Bay Times Peterman Scholarship awards. Scholarships are worth up to $3,500 depending on your academic status. The Peggy Peterman Scholarship targets minority students in journalism and is worth $5,000 and includes a paid internship at the Times. Applicants must be full-time undergraduate or graduate minority students who are pursuing careers in journalism. Specify in your application whether you're applying for the Peterman Scholarship/News Internship.", url: "http://company.tampabay.com:2052/times-fund/scholarships", isLiked: false))
        internshipArray.append(Internship(title: "UNCF/Carnival Corporate Scholars Program", company: "Carnival Corp.", location: "Nationwide", description: "The UNCF/Carnival Corporate Scholars Program, sponsored in partnership with Carnival Corporation, is looking for college sophomores who are interested in pursuing a career in the hospitality industry and whose experience in their first two years of college demonstrates leadership and strategic and analytical ability. Candidates will be placed in a two-year scholarship and internship at various Carnival Corporation host sites. For the Minority sophomore undergraduate student enrolled full-time at a U.S. located, accredited four-year institution or a transfer student from a community college that has been accepted into an accredited four-year college or university, Community college students should select four-year under the enrollment status within the application, minimum GPA of 2.75; minimum GPA of 3.0 required for renewal, U.S. citizen or a permanent resident, majoring in hospitality management and/or administration, tourism, culinary arts, business, finance, communications, marketing or related field.", url: "https://scholarships.gmsp.org/Program/Details/39a4e769-abbf-467c-9af8-8f0163bfee37", isLiked: false))
        // MARK - 5
        internshipArray.append(Internship(title: "Bilingual Internship - PR & Influencer Marketing", company: "H+M Communications", location: "Los Angeles, CA", description: "H+M Communications is a full-service boutique and consumer-marketing consultancy with offices located in Los Angeles, New York, Miami and Seattle. H+M is dedicated to multicultural marketing with special focus on the U.S. Hispanic market and has become one of the top multicultural agencies trusted by many brands, film studios, television networks, content producers and distributors over the past fifteen years. H+M's expertise spans media and community relations, influencer outreach, grassroots/experiential marketing, and sponsorship development and activation. Some of our clients include: Universal Pictures, Telemundo, Fox Searchlight, Paramount, Comcast, Pantelion, STRONG by Zumba, and Sony Pictures Television among others.", url: "https://www.indeed.com/q-PR-Marketing-Internship-jobs.html?vjk=8a88bf619b55b7b2", isLiked: false))
        internshipArray.append(Internship(title: "CONGRESSIONAL INTERNSHIP PROGRAM", company: "Congressional Hispanic Caucus Institute", location: "Washington, D.C.", description: "CHCI Interns will meet accomplished leaders—including CHCI Alumni dedicated to improving the Hispanic/Latino community. These alumni are from a wide range of professional backgrounds, including Capitol Hill, Fortune 500 companies, NGOs, nonprofits, and many other organizations.", url: "https://chci.org/programs/congressional-internship-program/", isLiked: false))
        internshipArray.append(Internship(title: "Inroads", company: "INROADS", location: "Varies", description: "INROADS accepts applications year-round, however for priority consideration, it is recommended college undergraduates submit their online internship application by March 31st. The INROADS Application is the first step to becoming an INROADS Intern. Students applying to Canada or Mexico opportunities should email recruitment@inroads.org for unique application qualifications.", url: "https://inroads.org/internships/apply/", isLiked: false))
        internshipArray.append(Internship(title: "ACLU Immigrants' Rights Project Undergraduate Internship Program", company: "ACLU", location: "Varies", description: "The ACLU is an equal opportunity employer and values a diverse workforce.  The ACLU encourages applications from all qualified individuals without regard to race, color, religion, gender, sexual orientation, gender identity or expression, age, national origin, marital status, citizenship, disability, veteran status, and record of arrest or conviction. The ACLU uses affirmative action strategies in recruitment and employment efforts to assure that persons with disabilities have full opportunities for employment in all positions. Applicants are not required or expected to provide any current salary and compensation information, or salary history during any phase of the recruitment process.", url: "https://www.aclu.org/careers", isLiked: false))
        internshipArray.append(Internship(title: "American Economic Association Summer Minority Program", company: "American Economic Association", location: "Chicago, IL", description: "Since 1974, the AEA Summer Training Program and Scholarship Program have increased diversity in the field of economics by preparing talented undergraduates for doctoral programs in economics and related disciplines. AEASP is a opportunity that enables students to develop technical skills to prepare for their graduate studies. As many as 20% of PhDs awarded to minorities in economics over the past 20 years are graduates of this program. Students receive 2 months of intensive training in microeconomics, math, econometrics and research methods. At 3 credits per class, students have the opportunity to earn 12 college credits.", url: "https://scholarships.gmsp.org/Program/Details/39a4e769-abbf-467c-9af8-8f0163bfee37", isLiked: false))
        // MARK - 10
        internshipArray.append(Internship(title: "Center for the Advancement of Hispanics in Science and Engineering Education", company: "CASHEE", location: "Landover, MD", description: "The Center for the Advancement of Hispanics in Science and Engineering Education is a national educational and scientific non-profit organization based in Washington DC created by Latino scientists and engineers. Their mission is to prepare talented Hispanic and other underrepresented minority science and engineering students reach academic excellence and professional success through CAHSEE's rigorous education and leadership development programs.", url: "http://www.cahsee.org/", isLiked: false))
        internshipArray.append(Internship(title: "Diversity Programs", company: "Barclays", location: "Varies", description: "The diversity programs offers a wide range of career opportunities to help expand your learning. You'll find an overview of all our diversity programs below, so use our dropdown filters to find the ones that suit you best. Click 'Find out more' to learn more", url: "https://joinus.barclays/americas/diversity-programs/", isLiked: false))
        internshipArray.append(Internship(title: "ASPIRA Programs", company: "ASPIRA", location: "Varies", description: "ASPIRA has had over forty-nine years of experience creating and implementing  informal education programs that build up self-esteem, cultural awareness, and leadership abilities.", url: "http://www.aspira.org/book/programs", isLiked: false))
        internshipArray.append(Internship(title: "The HACU National Internship Program (HNIP)", company: "Hispanic Association of Colleges and Universities", location: "Varies", description: "The HACU National Internship Program partners with some of the leading corporations in the nation to help them hiring the best talent from HACU member colleges and universities. The process is very competitive and rewarding because many internships lead to full-time roles. Opportunities for both internships and full-time employment are available.", url: "https://www.hacu.net/hacu/Corporate_HACU_Internship_Program.asp", isLiked: false))
        internshipArray.append(Internship(title: "Coro Kansas City-Summer Internship in Public Affairs", company: "Coro", location: "Kansas City", description: "The Summer Internship in Public Affairs is a full-time, ten-week summer program, whose purpose is to develop future community leaders through exposure to community issues, skill development, civic leaders and organizations. The program is demanding, full-time, and requires an interest in public affairs. Each intern is assigned an individual internship in business, government, labor, media, or non-profit organizations. A preference in consideration is given to applicants from the Greater Kansas City area or to those who intend to include Kansas City in their future plans. Both undergraduate and graduate students are eligible to apply. Twelve interns are selected every summer. Interns receive compensation.", url: "http://www.coro.org", isLiked: false))
        // MARK - 15
        // MARK - 20
        internshipArray.append(Internship(title: "National Association for Stock Car Auto Racing (NASCAR)-Diversity Internship Program", company: "NASCAR", location: "Landover, MD", description: "The NASCAR Diversity Internship Program will employ college/university students in a ten-week summer program designed to introduce them to the world of NASCAR and the exciting career opportunities available in the motorsports industry. The program is designed to support students with an interest in the motorsports industry, who are of Alaskan Native, American Indian, Asian/Pacific Island, African American,Hispanic, or of other racial minority descent. The internships are nationwide in several industry fields, including broadcasting, sales, and sports marketing. In addition to a salary, interns receive a monthly housing compensation. ", url: "http://www.diversityinternships.com", isLiked: false))
        internshipArray.append(Internship(title: "University of Michigan, School of Public Health-Summer Enrichment Program for Minority Undergraduates", company: "University of Michigan", location: "Detroit/Ann Arbor", description: "Every summer, 18-25 undergraduate students from across the country come to Ann Arbor for eight weeks of education, mentoring, internships with health care organizations in Southeast Michigan, and preparation for graduate school success. Since the program's inception in 1986, more than 90% of its participants have completed graduate study in public health, medicine, health sciences, and business. Most alumni have gone on to successful careers in public health and healthcare management, with many holding senior management positions in health systems, hospitals, community health centers, health policy organizations, and numerous other health enterprises.", url: "http://www.sph.umich.edu/hmp/sep_hmp.html", isLiked: false))
        internshipArray.append(Internship(title: "The University of Pennsylvania School of Medicine", company: "UPenn", location: "Philadelphia, PA", description: "The University of Pennsylvania School of Medicine offers a pre-med enrichment program for minority students. This program prepares students for careers in academic medicine or other positions of leadership in 50 medicine. Over ten weeks, beginning in late May, student who have completed two years of undergraduate education, will be engaged in a program of research, clinical observations, classroom exercises and teaching observations, designed to stimulate their interest in academic medicine. In addition, the students will be engaged in the following: activities pertaining to the medical school application process and medical school admissions; classroom instructions and simulated testing to prepare the students for the Medical College Admissions Test (MCAT). Housing and two meals a day (Monday - Friday) will be provided. Participants will also receive compensation.", url: "http://www.uphs.upenn.edu/coeomh/premed.htm", isLiked: false))
        internshipArray.append(Internship(title: "University of Pittsburgh Carnegie Mellon MD/PHD Program", company: "University of Pittsburgh, MSTP", location: "Pittsburgh, PA", description: "The Pittsburgh MD/PHD Program offers a 10-week summer research and enrichment program for underrepresented minority students interested in careers as physician scientists. The program is designed for students in their freshman, sophomore or junior years of college. Students receive a stipend for the ten-week period plus round trip airfare. This stipend provides students with a comfortable budget to live in Pittsburgh. All students must have medical insurance for the duration of the program, and since they will be working with human materials, are encouraged to be vaccinated for hepatitis B.", url: "http://www.mdphd.pitt.edu", isLiked: false))
        internshipArray.append(Internship(title: "Wake Forest University School of Medicine-Cardiovascular Summer Research Program", company: "Wake Forest University School of Medicine", location: "Winston-Salem, NC", description: "The Summer Internship in Public Affairs is a full-time, ten-week summer program, whose purpose is to develop future community leaders through exposure to community issues, skill development, civic leaders and organizations. The program is demanding, full-time, and requires an interest in public affairs. Each intern is assigned a brief, individual internship in business, government, labor, media, or non-profit organizations. Preferential consideration is given to applicants from the Greater Kansas City area or to those who intend to include Kansas City in their future plans. Both undergraduate and graduate students are eligible to apply. Twelve interns are selected every summer. Interns receive a stipend.", url: "http://www1.wfubmc.edu/Hypertension/ ", isLiked: false))
        // MARK - 25
        internshipArray.append(Internship(title: "Institute for Humane Studies-Charles G. Koch Summer Fellow Program", company: "Institute for Humane Studies", location: "George Mason University", description: "The Charles G. Koch Summer Fellow Program provides students with the opportunity to work with top policy experts, journalists, and academics. The fellows work with one of the area's many research institutes developing market solutions to today's critical policy problems or at a public interest law firm defending economic and political liberties. Fellows receive a stipend, housing, roundtrip transportation, and attend career workshops.", url: "http://www.theihs.org", isLiked: false))
        internshipArray.append(Internship(title: "Legal Momentum", company: "Legal Momentum", location: "See website", description: "Legal Momentum advances the rights of women and girls by using the power of the law and creating innovative public policy. Legal Momentum seeks candidates with a demonstrated interest in women's issues, the law, education and/or public policy for internships and volunteer positions. Undergraduate interns and volunteers assist in various aspects of the National Judicial Education Program and the Communications, Development and Legal Information and Referral. During the academic year, interns are required to work a minimum of eight hours per week. Summer interns work at least 30 hours each week and participate in seminars and brown bag lunches sponsored by the Everett Internship Program. Legal Momentum offers various internships, including accounting, child care policy, public education and outreach, and legal. Internships are available throughout the year and in Washington, D.C. and New York City. Undergraduate, graduate, and law students are eligible to apply.", url: "http://www.legalmomentum.org/about/intern_under.shtml", isLiked: false))
        internshipArray.append(Internship(title: "The University of Pennsylvania School of Medicine", company: "UPenn", location: "Philadelphia, PA", description: "The University of Pennsylvania School of Medicine offers a pre-med enrichment program for minority students. The aim of this program is to prepare students for careers in academic medicine or other positions of leadership in 50 medicine. Over ten weeks, beginning in late May, student who have completed two years of undergraduate education, will be engaged in a program of research, clinical observations, classroom exercises and teaching observations, designed to stimulate their interest in academic medicine. In addition, the students will be engaged in the following: activities pertaining to the medical school application process and medical school admissions; classroom instructions and simulated testing to prepare the students for the Medical College Admissions Test (MCAT). Housing and two meals a day (Monday - Friday) will be provided. Participants will also receive a stipend.", url: "http://www.uphs.upenn.edu/coeomh/premed.htm", isLiked: false))
        internshipArray.append(Internship(title: "National Center for Ethics-Health Care Ethics Internships", company: "National Center for Ethics", location: "Washington, DC", description: "The National Center for Ethics of the Veterans Health Administration (VHA) is a national program that supports the largest integrated health care delivery system in the nation through consultation, education, networking and communications, policy development, and evaluation. Interns can choose to work in close collaboration with the Center’s multidisciplinary team of professionals at one of the Center’s four sites: Washington, DC, New York, NY, White River Junction, VT, or Seattle, WA. College graduates and graduate students are eligible to apply. The internships generally last 10 weeks (most beginning in June) and interns will receive a stipend of up to $2,400. Candidates from medicine, other health professions, law, theology, health administration, and disciplines relevant to ethics are invited to apply.", url: "http://www.va.gov/vhaethics/index.cfm", isLiked: false))
        internshipArray.append(Internship(title: "National Partnership for Women and Families", company: "NPWF", location: "Washington, DC", description: "The National Partnership for Women and Families is a non-profit, non-partisan organization that uses public education and advocacy to promote fairness in the workplace, quality health care, and policies that help women and men meet the dual demands of work and family. The National Partnership invites bright, energetic women and men who are passionate about our issues to apply for internships. This is an opportunity to learn from seasoned professionals, to work inside the advocacy/public policy community, and to advance issues that have a direct impact on women and families nationwide. The National Partnership for Women and Families seeks interns for various positions. Internships are unpaid and are offered throughout the year.", url: "http://www.nationalpartnership.org", isLiked: false))
        // MARK - 30
        internshipArray.append(Internship(title: "Women’s Research and Education Institute (WREI)", company: "WREI", location: "Washington, DC", description: "The Women's Research and Education Institute (WREI) is a non-profit and non-partisan organization that provides information and analyses on issues of concern to women, policy makers, and others interested in women's issues. WREI offers unpaid internships to current undergraduate students. Interns assist WREI staff on various projects. Depending on the time of the year and what projects are on the front burner interns may help organize Capitol Hill briefings and conferences on key issues, prepare fact sheets on various topics, assist with preparations for fund-raising events, and represent WREI at Washington-area seminars and other events.", url: "http://www.wrei.org", isLiked: false))
        internshipArray.append(Internship(title: "Albert Einstein College of Medicine of Yeshiva University-Minority Student Summer Research Opportunity", company: "Minority Student Summer Research Opportunity Program", location: "Bronx, New York", description: "MSSROP will provide participants with nine weeks of research experience in conducting biomedical research. Students participating in the program will conduct research under the direction of a faculty member at the Albert Einstein College of Medicine. Research assignments will be made based upon availability of research opportunities and according to the mutual interests of the faculty sponsors and student participants. In addition to research training, participants will attend a special seminar/lecture series. Frequent meetings with other program participants along with one or more of the faculty sponsors will be scheduled as well as weekly seminars, workshops and lectures. At the end of the 9 week period, each student will present her or his work to other students and the faculty sponsors. Each student will also be expected to write a report concerning the research work conducted and its relation to other work in progress at her or his site. College sophomores or juniors are encouraged to apply. Campus housing will be available at no cost for students not able to commute. ", url: "http://www.rit.edu/~gtfsbi/Symp/aecom.htm", isLiked: false))
        internshipArray.append(Internship(title: "Princeton University, Woodrow Wilson School of Public and International Affairs-Junior Summer Institute ", company: "Princeton University", location: "Princeton, NJ", description: "The Junior Summer Institute is a seven-week program structured to introduce or strengthen skills in economics, statistics, policy analysis, writing, public speaking, and organization/time management. At the end of the sevenweek program, students will be able to present a comprehensive final report on a current policy issue that will encompass the skills acquired in their coursework, field research, policy analysis, and writing and computer workshops. Participants receive a stipend and funding for tuition and on-campus expenses. The program provides campus housing and meals. ", url: "http://www.wws.princeton.edu/jsi/welcome.html", isLiked: false))
        internshipArray.append(Internship(title: "U.S. Department of State-Student Internships", company: "U.S. Department of State", location: "Washington, DC", description: "The U.S. Department of State is the official international relations arm of the President of the United States and it is responsible for formulating, implementing, and supporting U.S. foreign policy. Students of all levels will find that the U.S. Department of State is a rewarding place to acquire skills that will last a lifetime. The Department of State has a variety of programs, from summer clerical positions to management fellowships, all of which allow students from high school to the post-graduate level the ability to participate in projects vital to the success of U.S. foreign policy. Internships are available overseas or in Washington D.C. The majority of internships are unpaid.", url: "http://www.careers.state.gov/student ", isLiked: false))
        internshipArray.append(Internship(title: "The Headlands Indian Health Careers Program", company: "Headlands Program", location: "Oklahoma City, OK", description: "Headlands Indian Health Careers is an intense academic enrichment and reinforcement program consisting ofmini-block courses in calculus, chemistry, physics, biology, writing and other communication skills. Courses are designed to increase the student's background and skills so s/he is better prepared for required college-level math and science course work in pre-health programs. These courses improve study habits for college work, raise the student's chances of success in college, and increase the probability of admission to a health professional school. Topics are presented in a series of lectures and laboratories, supplemented with individual tutorials. The program also informs students of the variety of health careers available, especially the need for American Indian health professionals. Special lectures concerning medicine and the healing arts in American Indian culture will be given by prominent American Indian health personnel. The program is aimed at high school seniors and college freshmen and runs from June to July. Older students may be interested in counselor positions", url: "http://www.headlands.ouhsc.edu/", isLiked: false))
        // MARK - 35
        internshipArray.append(Internship(title: "Harvard Business School-Summer Venture in Management Program (SVMP)", company: "Harvard Business School", location: "Boston, MA", description: "The Summer Venture in Management Program, a week-long program at the Harvard Business School, is designed to expose talented minority college students to general management in the business world. Using the renowned case method of instruction, HBS faculty lead class discussions on current management issues. Participants spend evenings analyzing real-business cases, and use morning study groups and classes to examine and debate their ideas through lively interaction with peers and faculty. This is the life of an MBA student at HBS. The academic program is supplemented by presentations from HBS administrators and alumni who provide information about the impact that an MBA degree can have on their lives and careers. Applicants must have completed their junior year of college.", url: "http://www.hbs.edu/mba/svmp/", isLiked: false))
        internshipArray.append(Internship(title: "MANA Internship Program", company: "Minority Student Summer Research Opportunity Program", location: "Bronx, New York", description: "MANA, a National Latina Organization, is a national membership organization that empowers Latinas through leadership development and community action. Through the support of General Motors and the Verizon Foundation, MANA is able to provide small stipends to summer interns at the Chapter level and the National level. High school and college Latina students will be able to intern at one of the organization’s chapters or at the national office in Washington, DC, supporting MANA community programs, especially the Hermanitas Program. 8 Students will acquire valuable skills and networking opportunities that will help them in their future careers. For an internship at one of MANA’s chapters, students need to contact their local chapter. For an internship in Washington, DC, students need to contact MANA’s national office.", url: "http://www.hermana.org", isLiked: false))
        internshipArray.append(Internship(title: "National Hispana Leadership Institute-Latinas Learning to Lead Summer Youth Institute", company: "Latinas Learning to Lead Summer Institute", location: "Arlington, VA", description: "The National Hispana Leadership Institute (NHLI) Latinas Learning to Lead Summer Youth Institute’s main purpose is to train the next generation of Latina leaders. It combines leadership training with technical and practical experience in a one-week comprehensive program in Washington, DC. The Institute focuses on personal and career planning, health and well-being, entrepreneurship, and leadership skills. Participants will have the opportunity to interact with high level Latina/o leaders during lectures, group exercises, and site visits. Young Latinas between the ages of 17 and 22 who are currently enrolled in an undergraduate program are eligible to apply. Requirements include a 2.5 GPA, demonstrated leadership, and a strong commitment to Latina/o issues. Up to 20 Latina undergraduate college students from diverse geographical areas and ethnic subgroups within the Hispanic community will be selected each year. NHLI will cover airfare, room and board, and all classroom materials needed for the program. ", url: "http://www.nhli.org/leader.htm", isLiked: false))
        internshipArray.append(Internship(title: "New America Alliance", company: "New America Alliance, Inc.", location: "Washington, DC", description: "New America Alliance is an organization of American Latino business leaders united to promote the economic advancement of the American Latino community, with a focus on economic and political empowerment and public advocacy to improve the quality of life in the United States. Each spring, fall and summer, New America Alliance offers internship positions for dedicated college students or recent graduates to assist on its economic and political capital agenda, its philanthropy and human capital initiatives, and in the areas of membership and marketing. Interns work a minimum of 32 hours per week and receive a monthly stipend. ", url: "http://www.naaonline.org", isLiked: false))
        internshipArray.append(Internship(title: "Associated Press (AP)-Internship Program", company: "Associated Press", location: "Varies", description: "The AP Internship Program is a highly competitive, 12-week, individually tailored training program for students who are aspiring print, photo, graphics, radio broadcast, and multimedia journalists. Up to 22 interns are selected each year to train in a domestic AP bureau under the supervision of a designated trainer. Internships are paying. Start dates are flexible.", url: "http://www.headlands.ouhsc.edu/", isLiked: false))
        // MARK - 40
    }
    
    private func setupScholarships() {
        scholarshipArray.append(Scholarship(title: "¡Adelante! Fund Ford Motor Company/Future Leaders Scholarship", amount: "$1,500", deadline: "Deadline Varies", description: "The ¡Adelante! U.S. Education Leadership Fund is a leadership development, non-profit organization dedicated to college students of Hispanic descent. Their mission is to inspire the best and brightest Latino students to graduate and lead through scholarships, internships, and leadership training. Applicants must have completed at least 30 credit hours of college coursework prior to the upcoming fall academic period and must have attended a San Antonio area high school and be a U.S. Citizen or permanent resident who is of Hispanic descent with a minimum 2.75 GPA. Must maintain full-time enrollment status (12 hours) for the duration of the scholarship period.", url: "https://www.adelantefund.org/#!scholarships/cee5", isLiked: false))
        scholarshipArray.append(Scholarship(title: "¡Adelante! Fund Gilbert G. Pompa Memorial Scholarship", amount: "$1000", deadline: "July 03, 2019", description: "The ¡Adelante! U.S. Education Leadership Fund is a leadership development, non-profit organization dedicated to college students of Hispanic descent. Their mission is to inspire the best and brightest Latino students to graduate and lead through scholarships, internships, and leadership training. Applicants must have completed at least 30 credit hours of college coursework prior to the upcoming fall academic period and must have attended a San Antonio area high school and be a U.S. Citizen or permanent resident who is of Hispanic descent with a minimum 2.75 GPA. Must maintain full-time enrollment status (12 hours) for the duration of the scholarship period.", url: "https://www.adelantefund.org/#!scholarships/cee5", isLiked: false))
        scholarshipArray.append(Scholarship(title: "¡Adelante! Fund MillerCoors Colorado Scholarship", amount: "$3000", deadline: "July 03, 2019", description: "The ¡Adelante! U.S. Education Leadership Fund is a leadership development, non-profit organization dedicated to college students of Hispanic descent. Their mission is to inspire the best and brightest Latino students to graduate and lead through scholarships, internships, and leadership training. Applicants must have completed at least 30 credit hours of college coursework prior to the upcoming fall academic period and must have attended a San Antonio area high school and be a U.S. Citizen or permanent resident who is of Hispanic descent with a minimum 2.75 GPA. Must maintain full-time enrollment status (12 hours) for the duration of the scholarship period.", url: "https://www.adelantefund.org/#!scholarships/cee5", isLiked: false))
        scholarshipArray.append(Scholarship(title: "¡Adelante! Fund MillerCoors Engineering and Science Scholarship", amount: "$3000", deadline: "July 03, 2019", description: "The ¡Adelante! U.S. Education Leadership Fund is a leadership development, non-profit organization dedicated to college students of Hispanic descent. Their mission is to inspire the best and brightest Latino students to graduate and lead through scholarships, internships, and leadership training. Applicants must have completed at least 30 credit hours of college coursework prior to the upcoming fall academic period and must have attended a San Antonio area high school and be a U.S. Citizen or permanent resident who is of Hispanic descent with a minimum 2.75 GPA. Must maintain full-time enrollment status (12 hours) for the duration of the scholarship period.", url: "https://www.adelantefund.org/#!scholarships/cee5", isLiked: false))
        scholarshipArray.append(Scholarship(title: "¡Adelante! HOPE Alamo Community College District Scholarship", amount: "$1000", deadline: "March 18, 2019", description: "The ¡Adelante! U.S. Education Leadership Fund is a leadership development, non-profit organization dedicated to college students of Hispanic descent. Their mission is to inspire the best and brightest Latino students to graduate and lead through scholarships, internships, and leadership training. Applicants must have completed at least 30 credit hours of college coursework prior to the upcoming fall academic period and must have attended a San Antonio area high school and be a U.S. Citizen or permanent resident who is of Hispanic descent with a minimum 2.75 GPA. Must maintain full-time enrollment status (12 hours) for the duration of the scholarship period.", url: "https://www.adelantefund.org/#!scholarships/cee5", isLiked: false))
        // MARK - 5
        scholarshipArray.append(Scholarship(title: "ALLIES Scholarship for Student Leadership Development", amount: "$500", deadline: "March 15, 2019", description: "Applicants must be full-time students at Northern Michigan University in good academic standing and have shown leadership, support, or involvement in organizations, activities, or issues that promote awareness and acceptance of the LGBTQIA Northern Michigan University.", url: "http://www.nmu.edu/multiculturaledandres/node/9#__utma", isLiked: false))
        scholarshipArray.append(Scholarship(title: "Audria M. Edwards Scholarship Fund", amount: "Varies", deadline: "May 01, 2019", description: "The Audria M. Edwards Scholarship Fund is for students who will be pursuing undergraduate education in an accredited institution or program during the coming school year and who are lesbian, gay, bisexual, or transgender or have a LGBT parent. Applicants must have resided for at least one year in the State of Oregon or in Clack, Cowlitz, Skamania, or Wahkiakum Counties in Washington.", url: "http://www.peacockinthepark.org/scholarship/", isLiked: false))
        scholarshipArray.append(Scholarship(title: "Better Brothers LA Book Scholarship", amount: "Varies", deadline: "January 19, 2019", description: "Better Brothers LA assists Black LGBTQ youth with avoiding financial hindrances imposed by school-related feed by offering scholarships. The scholarships support youth who have been admitted to or are attending an accredited degree, licensing or vocational program anywhere in the country.", url: "http://betterbrothersla.com/book-scholarship.shtml", isLiked: false))
        scholarshipArray.append(Scholarship(title: "CFPCA LGBT Endowed Scholarship", amount: "$500", deadline: "February 01, 2019", description: "The CFPCA LGBT Endowed Scholarship provides financial support and hope to students who demonstrate positive sensitivity to and involvement in LGBT issues. Preference is given to LGBT students although all students are invited to apply. All current undergraduate and graduate students must be enrolled at least half-time with majors in the College of Fine, Performing and Communication Arts who are in good academic standing may apply.", url: "http://cfpca.wayne.edu/scholarships.php", isLiked: false))
        scholarshipArray.append(Scholarship(title: "Chely Wright Like Me Scholarship", amount: "$1250", deadline: "May 31, 2019", description: "The Chely Wright LIKE ME Scholarship provides financial support for students pursuing a college degree who actively advocate for LGBT youth and to students who have been affected by teen bullying or suicide of an LGBT youth. Through this scholarship, LGBT affected youth can apply for a chance to have their educational expenses paid and to pursue a degree from an accredited college, university, or technical/vocational program. Graduating high school seniors who can show that they have actively advocated for LGBT issues, such as respect and inclusion for LGBT youth, community service at an LGBT resource, involvement and/or attendance of LGBT events, working against teen bullying or teen suicide, and any other activities that improve the condition of the LGBT community and/or improve cultural conditions for LGBT youth are eligible to apply. For more information or to apply, please visit the scholarship provider's website.", url: "http://likeme.org/chely-wright-scholarship/", isLiked: false))
        // MARK - 10
        scholarshipArray.append(Scholarship(title: "Ann Seki Memorial Scholarship", amount: "Varies", deadline: "April 30, 2019", description: "This scholarship is sponsored by Chevron and is awarded in memory of Ann Seki, an original member of the Chevron Hispanic Recruiting Team. Ann Seki had a determined viewpoint in ensuring Chevron met diversity hiring goals and was instrumental in developing a process to identify and select Chevron employees for higher recognition outside Chevron. This scholarship has been awarded since 2010. Eligibility: Hispanic/Latino, be a freshmen, sophomore, or junior in college, major in Engineering (Civil, Chemical, Electrical, Facilities, Mechanical, and Petroleum), minimum 3.3 GPA, a U.S. Citizen/Permanent Resident", url: "http://www.greatmindsinstem.org/college/ann-seki-memorial-scholarship", isLiked: false))
        scholarshipArray.append(Scholarship(title: "APA Judith McManus Price Scholarship", amount: "$4000", deadline: "April 30, 2019", description: "Women and minority (African American, Hispanic American, or Native American) students enrolled in an approved Planning Accreditation Board planning program who are citizens of the United States, intend to pursue careers as practicing planners in the public sector, and are able to demonstrate a genuine financial need are eligible to apply for this scholarship.", url: "https://www.planning.org/foundation/scholarships/", isLiked: false))
        scholarshipArray.append(Scholarship(title: "APSA Minority Fellowship Program", amount: "$4000", deadline: "October 30, 2018", description: "Minority Fellows Program is a fellowship competition for individuals from under-represented backgrounds applying to doctoral programs in political science. Eligibility: Must be a member of one of the following racial/ethnic minority groups: African Americans, Asian Pacific Americans, Latinos/as, and Native Americans, be a college/university seniors, college/university graduates, or students currently enrolled in a master's program, demonstrate an interest in teaching and potential for research in political science, be a U.S. citizen.", url: "https://www.apsanet.org/mfp", isLiked: false))
        scholarshipArray.append(Scholarship(title: "ASA Minority Fellowship Program", amount: "$18000", deadline: "January 31, 2019", description: "Minority Fellowship Program applicants can be new or continuing graduate students. However, the MFP is primarily designed for minority students entering a doctoral program in sociology for the first time or for those who are in the early stages of their graduate programs. MFP applicants must be applying to or enrolled in sociology departments which have strong mental health research programs and/or faculty who are currently engaged in research focusing on mental health issues. MFP fellows are selected on the basis of their commitment to research in mental health and mental illness, academic achievement, scholarship, writing ability, research potential, financial need, and racial/ethnic minority background. Specifically, applicants must be members of one of the following racial/ethnic groups: Blacks/African Americans, Latinos/as (e.g., Mexican Americans, Puerto Ricans, Cubans), American Indians or Alaskan Natives, and Asians (e.g., Chinese, Japanese, Korean, Southeast Asian), or Pacific Islanders (e.g., Hawaiian, Guamanian, Samoan, Filipino).", url: "http://www.asanet.org/career-center/grants-and-fellowships/minority-fellowship-program", isLiked: false))
        scholarshipArray.append(Scholarship(title: "ALA - LITA/LSSI Scholarship", amount: "$2500", deadline: "March 01, 2019", description: "ACS awards renewable scholarships to underrepresented minority students who want to enter the fields of chemistry or chemistry-related fields. African American, Hispanic, or American Indian high school seniors or college freshman, sophomores, or juniors pursuing a college degree in the chemical sciences or chemical technology are eligible to apply for this scholarship. To be considered for a scholarship through the ACS Scholars Program, candidates must: be African-American, Hispanic/Latino, or American Indian, be a U.S. citizen or permanent U.S. resident, be a full-time student at a high school or accredited college, university, or community college, demonstrate high academic achievement in chemistry or science with a 3.0+ GPA, demonstrate financial need according to the Free Application for Federal Student Aid form (FAFSA) and the Student Aid Report (SAR) form, be a graduating high school senior or college freshman, sophomore or junior intending to or already majoring in chemistry, biochemistry, chemical engineering or a chemically-related science OR intending to or already pursuing a degree in chemical technology, be planning a career in the chemical sciences. Please note that students intending to enter Pre-Med programs or pursuing a degree in Pharmacy are not eligible for this scholarship. For more information or to apply, please visit the scholarship provider's website.", url: "http://www.ala.org/lita/awards/lssi", isLiked: false))
        scholarshipArray.append(Scholarship(title: "Augustana University Diversity Scholarships", amount: "Varies", deadline: "Varies", description: "Diversity Scholarships are for full-time students who are members of a minority ethnic group and bring diversity to campus. Ethnicity and financial need are two of the factors considered. Verify your eligibility with the Office of Admission or Financial Aid.", url: "http://www.augie.edu/admission/financing-your-education/scholarships", isLiked: false))
        // MARK - 15
        scholarshipArray.append(Scholarship(title: "Jesse L. Jackson-Fellows Toyota Scholarship", amount: "$20000", deadline: "May 01, 2019", description: "The Jesse Jackson Fellows-Toyota Scholarship is a renewable scholarship that awards up to $25,000 dollars annually to deserving African-American college sophomores. Students who are interested in applying for the scholarship must have a minimum cumulative 3.0 GPA, be a business or STEM (Science, technology, engineering and/or math) major that can be applied to the automotive industry, demonstrated participation in community service and need for financial assistance. For more information or to apply, please visit the scholarship provider's website.", url: "http://www.pushexcel.org/scholarships/", isLiked: false))
        scholarshipArray.append(Scholarship(title: "Jonathan LaRon Skinner Memorial Scholarship", amount: "$500", deadline: "April 01, 2019", description: "The Jonathan LaRon Skinner Memorial Scholarship was established by the family and friends of Jonathan Skinner in 2010 in memory of Jonathan LaRon Skinner to provide scholarships to graduating high school seniors. Applicants must attend a Forsyth County high school and reside in The Winston-Salem Foundation's service area with preference given to students attending Quality Education High School of Business and Entrepreneurship; have a minimum 3.0 GPA and be African American.", url: "https://www.wsfoundation.org/sslpage.aspx?pid=745", isLiked: false))
        scholarshipArray.append(Scholarship(title: "Juanita Crippen Memorial Scholarship", amount: "$500", deadline: "April 30, 2019", description: "To recognize a senior high school student from a migrant farm-worker family in Franklin, St. Lawrence, or Clinton Counties in New York State needing post-secondary scholarship assistance who has demonstrated a caring and giving attitude toward another individual or community with a scholarship. Requirements: Two reference letters from a school representative (such as a counselor, teacher, coach, or other) addressing your educational commitment, grades, etc. and supporting the need for financial assistance. People writing the reference letter cannot be anyone under 21 years of age, or anyone related to you or serving as a legal guardian. A personal essay must be included (250-300 words) with information about what service to others means to you and how you have benefited by assisting someone else. What did you learn from the experience? Must provide proof of acceptance/enrollment at a college/university, proof of migrant education eligibility with a Certificate of Eligibility (COE) showing qualifications as a migrant student during the past three years or any time during high school.", url: "http://migrant.net/migrant/scholarships/crippen.htm", isLiked: false))
        scholarshipArray.append(Scholarship(title: "Kahdine Ann DaCosta Scholarship for Excellence in Leadership", amount: "$1000", deadline: "March 01, 2019", description: "The Kahdine Ann DaCosta Memorial Scholarship for Excellence in Leadership was established on October 15, 2011 in honor of Kahdine Ann DaCosta. Every year, I AM O'KAH! searches for students that embody Kahdine’s tenacious drive and unwavering dedication to the community. Applicants must attend a high school in the Baltimore Metro area (Baltimore City, Baltimore County and Ann Arundel County) and be a senior in good standing, as defined by school and verified by official transcript. Applicants must have a minimum cumulative grade point average of 2.5 out of 4.0 or equivalent. Have demonstrated leadership abilities through their participation in community service, extracurricular activities, or other activities shown to foster leadership skills. A minimum of two consecutive years of community service/activities is required. Will enroll for the first time at an accredited two- or four-year college/university (including trade/vocational school where they will earn an associate degree) located in the United States in the upcoming academic year. Must demonstrate financial need which is verified through FAFSA.", url: "http://www.iamokah.org/scholarship/", isLiked: false))
        scholarshipArray.append(Scholarship(title: "Kevin W. Scott Memorial Scholarship", amount: "Varies", deadline: "February 15, 2019", description: "Kelvin W. Scott, an outstanding member of the basketball and track teams at Arthur Hill High School, set remaining track records before graduating in 1980. Kelvin continued on to be a Big Ten champion and record setter in indoor and outdoor track at Michigan State University in the 1 mile, 1,600 meter and the 4×400-meter relay teams in 1982 and 1983. After graduating from MSU in 1984, Kelvin went on to receive a Juris Doctorate degree from Georgetown University Law Center in 1987. An attorney in both corporate and governmental fields and a member of various legal organizations, Kelvin served as the director of the Michigan Department of Civil Rights at the time of his passing where he championed the rights of people without full equality in Michigan. Requirements: Graduating senior from Arthur Hill High School, Saginaw High School or Saginaw Arts & Sciences Academy, minimum 3.2 GPA, pursuing an undergraduate degree in pre-law.", url: "http://www.saginawfoundation.org/site/kelvin-w-scott-memorial-scholarship/", isLiked: false))
        // Mark - 20
        scholarshipArray.append(Scholarship(title: "Endowment for South Asian Students of Indian Descent Scholarship Fund", amount: "$2000", deadline: "September 30, 2018", description: "A $2,000 scholarship will be awarded to a qualified medical student. Eligibility: applicant must be a Pennsylvania resident for at least 12 months before registering as a medical student (not including time spent attending a Pennsylvania undergraduate or graduate school), must be a South Asian Indian or a descendant of a South Asian Indian immigrant to the United States; the following lineage qualifies: self, parent(s), grandparent(s), or great-grandparent(s) of South Asian Indian heritage, must be enrolled full-time in an accredited Pennsylvania medical school, must be enrolled or entering his/her second, third or fourth year of medical school, must have completed a FAFSA", url: "https://www.petersons.com/scholarship/endowment-for-south-asian-students-of-indian-descent-scholarship-111_166692.aspx", isLiked: false))
        scholarshipArray.append(Scholarship(title: "EPP Undergraduate Scholarship Program", amount: "$45000", deadline: "January 31, 2019", description: "The goal of the EPP Undergraduate Scholars Program is to increase the number of students who undertake course work and graduate with degrees in targeted academic fields integral to NOAA's mission. This program targets students who have completed their sophomore year, attending minority serving institutions, and have recently declared, or about to declare a major in atmospheric, oceanic, or environmental disciplines that support these sciences. Applicant must be a U.S. citizen currently enrolled or accepted as a full-time, second-year student in a four-year academic program or a third-year student in a five-year program in a discipline related to NOAA's programs and mission at an accredited minority-serving institution (college or university within the United States or U.S. territories). Applicants must earn and maintain a minimum 3.2 GPA.", url: "http://www.noaa.gov/office-education/epp-msi/undergraduate-scholarship", isLiked: false))
        scholarshipArray.append(Scholarship(title: "ESA Foundation Scholarship Program for Minority Students", amount: "$3000", deadline: "May 04, 2019", description: "The ESA Foundation scholarships are offered for full-time undergraduate study at accredited four-year colleges and universities in the USA. Up to 30 scholarships of $3,000 each will be awarded annually, 15 to graduating high school seniors and 15 to current college students. Women and minority students are eligible to apply, so long as they are U.S. citizens and have a minimum 2.75 GPA. Students must also be pursuing degrees leading to careers in computer and video game arts. For more information or to apply, please visit the scholarship provider's website.", url: "http://www.esafoundation.org/scholarship.asp", isLiked: false))
        scholarshipArray.append(Scholarship(title: "F.A. and Charlotte Blount Scholarship", amount: "$3000", deadline: "April 01, 2019", description: "The F.A. and Charlotte Blount Scholarship was established in 1997 to provide college scholarships to graduating Forsyth County high school seniors who will pursue a four-year baccalaureate degree at an accredited college or university. To receive consideration, applicants must be African-American or Hispanic, have a minimum 3.0 GPA and demonstrate financial need. For more information or to apply, please visit the scholarship provider's website.", url: "https://www.wsfoundation.org/document.doc?id=162", isLiked: false))
        scholarshipArray.append(Scholarship(title: "Fontana Transport Inc. Scholars Program", amount: "$5000", deadline: "March 14, 2019", description: "The Fontana Transport Inc. Scholars Program is open to underrepresented, low-income and first-generation college-bound students. Students must be pursuing an undergraduate degree full-time in transportation, math, science, engineering, architecture, environmental design, PreMed, psychology, Spanish language/literature. The applicant does not have to be a U.S. citizen but must have a minimum 3.5 GPA and proof of attending college beginning in the fall semester. Recommendation by a faculty member is optional but highly suggested. For more information or to apply, please visit the scholarship provider's website.", url: "https://www.scholarships.com/financial-aid/fontana-transport-inc-scholars-program/", isLiked: false))
        // MARK - 25
        scholarshipArray.append(Scholarship(title: "Gay Asian Pacific Alliance Foundation Scholarship", amount: "$5000", deadline: "June 30, 2019", description: "The purpose of the Gay Asian Pacific Alliance (GAPA) Foundation Scholarship is to provide financial assistance to students in high school, undergraduate, graduate or professional school or trade or vocational school who express activism in the Asian and Pacific Islander (API) and/or lesbian, gay, bisexual, transgender, and queer (LGBTQ) communities. Applicants should have a strong history of activism within either the API and/or LGBTQ communities; however, applicants need not identify as either to apply. Preference is given to those whose identity sides with the API or LGBT society.", url: "https://gapafoundation.org/scholarships/", isLiked: false))
        scholarshipArray.append(Scholarship(title: "George A. Strait Minority Scholarships", amount: "Varies", deadline: "Varies", description: "George A. Strait Minority Scholarships are awarded to college graduates with meaningful law library experience who are members of a minority group as defined by current U.S. government guidelines, are degree candidates in an accredited library or law school, and who intend to have a career in law librarianship. Applicants must show evidence of financial need. To apply for the George A. Strait Minority Scholarship, you must also qualify for one of the AALL Educational Scholarships.", url: "https://www.aallnet.org/education-training/scholarships/", isLiked: false))
        scholarshipArray.append(Scholarship(title: "GRCF Arts Council of Greater Grand Rapids Minority Scholarship", amount: "Varies", deadline: "April 01, 2019", description: "The Arts Council of Greater Grand Rapids Minority Scholarship is open to students of color (African-American, Asian, Hispanic, Native American, Pacific Islander) attending a non-profit public or private college/university majoring in fine arts. Applicants demonstrate financial need, be a Kent County resident, and have a minimum 2.5 GPA.", url: "https://www.petersons.com/scholarship/Arts-Council-of-Greater-Grand-Rapids-Minority-Scholarship-111_189180.aspx", isLiked: false))
        scholarshipArray.append(Scholarship(title: "GRCF Hackett Family Scholarship", amount: "Varies", deadline: "April 01, 2019", description: "Grand Rapids Community Foundation awards hundreds of scholarships annually, primarily to Kent County students bound for or in college, or those pursuing a technical career. To be eligible for the Hackett Family Scholarship, students must be seniors at, or have graduated from any Grand Rapids public high school and is an undergraduate attending an accredited college/university or skilled trade school of their choice. Preference is given to women of color. For more information or to apply, please visit the scholarship provider's website.", url: "https://www.grfoundation.org/apply-for-scholarships", isLiked: false))
        scholarshipArray.append(Scholarship(title: "GRCF Miller Johnson West Michigan Diversity Law School Scholarship", amount: "$5000", deadline: "April 01, 2019", description: "The Grand Rapids Community Foundation administers and awards the following Law Scholarships to students of color (African American, Asian, Hispanic, Native American, Pacific Islander). The Miller Johnson West Michigan Diversity Law School Scholarship is awarded to students of color currently residing in Michigan (with preference given to West Michigan residents) pursuing a law degree at any accredited law school in the United States. Students must demonstrate financial need and have a minimum 3.0 cumulative GPA.", url: "https://www.affordablecollegesonline.org/college-resource-center/scholarships-for-asian-and-pacific-islander-students/", isLiked: false))
        // MARK - 30
        scholarshipArray.append(Scholarship(title: "GE/LNESC Scholarship", amount: "$5000", deadline: "Varies", description: "The partnership between the General Electric Foundation and the LNESC Scholarship Program is intended to assist and encourage outstanding minority students in completing their college education. The program is directed specifically to disadvantaged minority students with career interests in business or engineering. Eligibility: be a minority student pursuing full-time studies leading to a bachelor's degree at an accredited college or university in the U.S., classified as a college, have a cumulative college grade point average of at least 3.25 on a 4.0 scale or the equivalent, a business or engineering major, a U.S. citizen or legal resident", url: "https://www.lnesc.org/gelnesc-scholarship", isLiked: false))
        scholarshipArray.append(Scholarship(title: "GE-NMF Primary Care Leadership Program (PCLP)", amount: "$5000", deadline: "January 31, 2019", description: "The GE-NMF Primary Care Leadership Program  is a six-week summer program that includes clinical experience, leadership training, and a service-learning project that focuses on barriers in healthcare. PCLP provides students with an opportunity to examine the challenges and rewards of primary care practice at community health centers (CHCs) across the United States. Medical students and graduate nursing and physician assistant students from underrepresented minorities or socioeconomically disadvantaged backgrounds are encouraged to apply.", url: "https://nmfonline.org/about-our-scholarships-and-awards/service-learning-programs/nmf-primary-care-leadership-program/", isLiked: false))
        scholarshipArray.append(Scholarship(title: "GRCF Arts Council of Greater Grand Rapids Minority Scholarship", amount: "Varies", deadline: "April 01, 2019", description: "The Arts Council of Greater Grand Rapids Minority Scholarship is open to students of color (African-American, Asian, Hispanic, Native American, Pacific Islander) attending a non-profit public or private college/university majoring in fine arts, including all visual and performing arts. Applicants must have financial need, be a Kent County resident, and have a minimum 2.5 GPA.", url: "https://www.petersons.com/scholarship/Arts-Council-of-Greater-Grand-Rapids-Minority-Scholarship-111_189180.aspx", isLiked: false))
        scholarshipArray.append(Scholarship(title: "George A. Strait Minority Scholarships", amount: "Varies", deadline: "Varies", description: "George A. Strait Minority Scholarships are awarded annually to college graduates with meaningful law library experience who are members of a minority group as defined by current U.S. government guidelines, are degree candidates in an accredited library or law school, and who intend to have a career in law librarianship. Applicants must show evidence of financial need. To apply for the George A. Strait Minority Scholarship, you must also qualify for one of the AALL Educational Scholarships.", url: "https://www.unigo.com/scholarships/all/George-A.-Strait-Minority-Scholarship/1004039", isLiked: false))
        scholarshipArray.append(Scholarship(title: "George Scott Jr. Memorial Scholarship", amount: "Varies", deadline: "May 15, 2019", description: "The George Scott Jr. Memorial Scholarship was established by Mr. Kent Hance in memory of his good friend George Scott Jr. to provide scholarships to students to attend Texas Tech University. Preference shall be given to academically-motivated African American students from Lubbock, Texas who will be attending Texas Tech University.", url: "https://www.cfwtx.org/current-scholarships", isLiked: false))
        // MARK - 35
        scholarshipArray.append(Scholarship(title: "Girls Who Illustrate Awesomeness Scholarship", amount: "$750", deadline: "Varies", description: "This is a scholarship opportunity for young women of color who are actively working to change the world. Applicants must be young women of color who are currently enrolled in college/university or will begin college/university in the spring semester and have a minimum of 3.0 GPA.", url: "http://simpli.works/scholarship/", isLiked: false))
        scholarshipArray.append(Scholarship(title: "GRCF Warner Norcross & Judd Paralegal and Legal Secretarial Scholarship", amount: "$2000", deadline: "April 01, 2019", description: "The Grand Rapids Community Foundation administers and awards the following Law Scholarships to students of color (African American, Asian, Hispanic, Native American, Pacific Islander). The Warner Norcross & Judd LLP Paralegal or Secretarial Scholarship is awarded to students of color residing in Michigan pursuing paralegal or legal secretarial studies at an accredited program located in Michigan", url: "https://www.scholarships.com/financial-aid/college-scholarships/scholarships-by-type/minority-scholarships/latino-scholarships/grcf-warner-norcross-and-judd-paralegal-and-legal-secretarial-scholarship/", isLiked: false))
        scholarshipArray.append(Scholarship(title: "Gwenn Steward Clements Scholarship", amount: "$1000", deadline: "April 01, 2019", description: "The Gwenn Steward Clements Scholarship provides scholarships to graduating high school seniors from Lexington Senior High School in Davidson County who possess outstanding oral and written skills and who will pursue undergraduate degrees from accredited post-secondary institutions. Students must have a minimum 3.25 GPA who is solid in English, possessing outstanding oral and written skills along with an A- average. Preference will be given to minority students, particularly African-Americans.", url: "https://www.wsfoundation.org/document.doc?id=291", isLiked: false))
        scholarshipArray.append(Scholarship(title: "Herman J. Neal Scholarship", amount: "$4000", deadline: "April 01, 2019", description: "The Herman J. Neal scholarship supports African-American students in their pursuit of an accounting education and the CPA designation. These scholarships support students with their junior or senior year, or with the additional year, needed to sit for the CPA Exam which can include graduate studies. Scholarships cover the costs of tuition, fees, and can include up to $500 in expenses for books and required classroom materials. They do not cover costs of CPA Exam review courses. A minimum 3.0 GPA is required. Students must plan to sit for the CPA exam in Illinois within three years of the application date and demonstrate progress in accounting courses.", url: "https://findyourscholarship.com/illinois-cpa-society-herman-j-neal-scholarship/", isLiked: false))
        scholarshipArray.append(Scholarship(title: "Historically Underrepresented Groups Scholarship (HUGS)", amount: "$5000", deadline: "January 29, 2019", description: "The SAA is committed to assisting individuals in realizing their goals of entering careers in archaeology by offering two categories of scholarships: the HUGS and the HUGS-IFR. The SAA Historically Underrepresented Groups Scholarship (HUGS) helps increase the number of under-represented minorities obtaining degrees in archaeology. It provides funding to minority archaeology students, helping them enhance their education and successfully prepare for a variety of careers in archaeology and heritage management. The scholarship is overseen by the Minority Scholarships Committee of the SAA.", url: "http://saa.org/AbouttheSociety/Awards/HistoricallyUnderrepresentedGroupsScholarship/tabid/1516/Default.aspx", isLiked: false))
        // MARK - 40
    }
}
